### ISSUE TITLE
Deprecation: project.getConvention()

### ISSUE THREAD

**Issue by C-Otto** [aaschmid/gradle-cpd-plugin#68]
With Gradle 8.2.1 and `--warning-mode all --stacktrace` I get:
```
The Project.getConvention() method has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.2.1/userguide/upgrading_version_8.html#deprecated_access_to_conventions
        at org.gradle.api.internal.project.DefaultProject.getConvention(DefaultProject.java:593)
        at de.aaschmid.gradle.plugins.cpd.CpdPlugin.lambda$null$8(CpdPlugin.java:141)
```

**Comment by danilovesky** [comment]
Came to report the same issue.
Just in case, here is Gradle docs link with deprecation details:
https://docs.gradle.org/8.2.1/userguide/upgrading_version_8.html#deprecated_access_to_conventions

**Comment by aaschmid** [comment]
Thanks for reporting. I would appreciate a PR as I don't know when I will have time to concentrated work on this the next weeks.

**Comment by aaschmid** [comment]
Is this still an issue @C-Otto (I am not sure and maybe you know by heart)?

**Comment by C-Otto** [comment]
I can reproduce this with Gradle 8.2.1 (as mentioned in this issue) and plugin version 3.3, same with Gradle 8.3 to 8.6.

With Gradle 8.11+ I'm unable to use v3.3, with Gradle 8.7 to 8.10 I see a similar error (maybe the deprecation was just rephrased). 

With Plugin v3.4 I don't see any issue with Gradle 8.2.1 to 8.10, and I'm still unable to use 8.11+.

With Plugin v3.5 I don't see any issue with any Gradle version (8.2.1 to 8.12).

Thanks for the fix - whenever that happened :)
