### ISSUE TITLE
Incompatible with Gradle 8.11: ClassNotFoundException: org.gradle.api.reporting.internal.TaskReportContainer

### ISSUE THREAD

**Issue by jhonnen** [aaschmid/gradle-cpd-plugin#76]
The plugin is currently not compatible with Gradle 8.11 because the internal class `TaskReportContainer` was removed.

```
org.gradle.api.tasks.TaskInstantiationException: Could not create task of type 'Cpd'.	
    at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:95)	
    ...
Caused by: java.lang.NoClassDefFoundError: org/gradle/api/reporting/internal/TaskReportContainer	
    at de.aaschmid.gradle.plugins.cpd.Cpd.<init>(Cpd.java:97)	
    ...
Caused by: java.lang.ClassNotFoundException: org.gradle.api.reporting.internal.TaskReportContainer	
    at de.aaschmid.gradle.plugins.cpd.Cpd.<init>(Cpd.java:97)	
    at de.aaschmid.gradle.plugins.cpd.Cpd_Decorated.<init>(Unknown Source)
```

**Comment by aaschmid** [comment]
Thanks @jhonnen for reporting is. Do you already have a fix in mind and would like to contribute with a PR?

**Comment by jhonnen** [comment]
I don't have an obvious solution at the moment. The Gradle API doesn't seem to support report containers in 3rd party plugins.
In Gradle 8.11 they are implemented as follows:

```
public class JacocoReportsContainerImpl extends DelegatingReportContainer<ConfigurableReport> implements JacocoReportsContainer {

    @Inject
    public JacocoReportsContainerImpl(Describable owner, ObjectFactory objectFactory) {
        super(DefaultReportContainer.create(objectFactory, ConfigurableReport.class, factory -> ImmutableList.of(
            // ...
        )));
    }
    // ...
}
```

Both DelegatingReportContainer and DefaultReportContainer are still internal. You could of course just use that new internal API if you're OK with dropping support for Gradle <8.11

**Comment by cyanotyp** [comment]
Some updates and useful resources, that might help  
- gradle 9.0 will also be affected
- 10 year old forums post https://discuss.gradle.org/t/how-do-you-create-a-reporting-plugin-without-using-internal-apis/3827
- 6 years old github issue https://github.com/gradle/gradle/issues/7063
- gradle reporting dsl: https://docs.gradle.org/current/dsl/org.gradle.api.reporting.Reporting.html
