### ISSUE TITLE
NullPointerException in Multi-Module Build

### ISSUE THREAD

**Issue by jnadler** [aaschmid/gradle-cpd-plugin#8]
Thanks for putting this together, it's great!

We're trying to use it with a multi-module build.  Running "gradle cpdCheck" works fine and finds duplicate code across modules.

However other tasks at the root level like "gradle compileJava" now fail with an exception:

    java.lang.NullPointerException: Cannot get property 'project' on null object
	at de.aaschmid.gradle.plugins.cpd.CpdPlugin$_apply_closure3.doCall(CpdPlugin.groovy:96)
	at     org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at     org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)

**Comment by aaschmid** [comment]
Thanks @jnadler for the reporting of this bug. I have just released v0.3. It now just tasks some hours until it is syncronized with Maven central.

**Comment by jnadler** [comment]
Thanks for fixing this, and so quickly!
